#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
TOPDIR="$DIR/../../"

# Set the name of the manifest file
MANIFESTFILE="$TOPDIR/manifest.json"

# Set the name of the output zip file
OUTPUTFILE="$DIR/../build/genee.$1.zip"


# Set the list of directories to include in the zip file
INCLUDEDIRS=("assets" "screenshots" "scripts")

# Set the list of file extensions to include in the zip file
INCLUDEEXTS=("js" "html")

# Set the placeholder in the manifest file
PLACEHOLDER="__BROWSER__"

# Set the replacement value for the placeholder
REPLACEMENT="$1"

# Create the list of files to include in the zip file
FILES=()
for ext in "${INCLUDEEXTS[@]}"; do
    FILES+=($(find "$TOPDIR" -maxdepth 1 -type f -name "*.$ext"))
done
for dir in "${INCLUDEDIRS[@]}"; do
    FILES+=($(find "$TOPDIR/$dir" -type f))
done
FILES+=("$MANIFESTFILE.$1")

mv "$MANIFESTFILE" "$MANIFESTFILE.bak"

# Copy the manifest file with the specified browser value
cp "$MANIFESTFILE.$1" "$TOPDIR/$MANIFESTFILE"
sed -i "s/$PLACEHOLDER/$REPLACEMENT/g" "$TOPDIR/$MANIFESTFILE"

# Create the zip file with the specified list of files
cd "$TOPDIR" && zip -r "$OUTPUTFILE" "${FILES[@]}"

# Remove the copied manifest file
rm "$MANIFESTFILE"
mv "$MANIFESTFILE.bak" "$MANIFESTFILE"
